#ifndef JIMOKOMI_GAME_CONFIG_H
#define JIMOKOMI_GAME_CONFIG_H

#define BALL_COUNT 100000U
#define SOURCE_VARIANT_COUNT 8U
#define PLAYER_INDEX 0U
#define WORLD_WIDTH 1920.0f
#define WORLD_HEIGHT 1080.0f
#define GRID_CELL_SIZE 96.0f
#define PHYSICS_PIXELS_PER_METER 100.0f
#define PHYSICS_EARTH_GRAVITY_MPS2 9.81f
#define PHYSICS_MIN_HZ 15.0f
#define PHYSICS_MAX_HZ 300.0f
#define PHYSICS_FRAME_BUDGET_HZ 30.0f
#define PHYSICS_MAX_SUBSTEPS 10U
#define PLAYER_MOVE_SPEED 160.0f
#define PLAYER_MOVE_SMOOTHING 0.085f
#define PLAYER_JUMP_IMPULSE 585.0f
#define WORLD_WALL_THICKNESS 32.0f
#define BALL_RADIUS (14.0f / 3.0f)
#define BALL_SPAWN_INTERVAL_SECONDS (0.01 / 3.0)
#define BALL_RANDOM_FORCE_STRENGTH 18.0f
#define BALL_RANDOM_FORCE_INTERVAL_SECONDS 0.08f

#endif
