#ifndef JIMOKOMI_GAME_CONFIG_H
#define JIMOKOMI_GAME_CONFIG_H

#define BALL_COUNT 5U
#define SOURCE_VARIANT_COUNT 8U
#define PLAYER_INDEX 0U
#define WORLD_WIDTH 1920.0f
#define WORLD_HEIGHT 1080.0f
#define GRID_CELL_SIZE 96.0f
#define PHYSICS_PIXELS_PER_METER 100.0f
#define PHYSICS_EARTH_GRAVITY_MPS2 9.81f
#define PHYSICS_MIN_HZ 15.0f
#define PHYSICS_MAX_HZ 300.0f
#define PHYSICS_FRAME_BUDGET_HZ 30.0f
#define PHYSICS_MAX_SUBSTEPS 10U
#define PLAYER_MOVE_SPEED 160.0f
#define PLAYER_MOVE_SMOOTHING 0.085f
#define PLAYER_JUMP_IMPULSE 585.0f
#define WORLD_WALL_THICKNESS 32.0f
#define BALL_RADIUS ((14.0f / 3.0f) * 20.0f)
#define BALL_DENSITY 0.35f
#define BALL_SPAWN_TOP_HEIGHT 180.0f
#define BALL_SPAWN_INTERVAL_SECONDS (0.05 / 3.0)
#define LIQUID_PARTICLE_RADIUS 5.0f
#define LIQUID_PARTICLE_STEP_ITERATIONS 4
#define LIQUID_PARTICLE_SOURCE_MAX_COUNT 5000U
#define LIQUID_PARTICLE_LIFETIME_SECONDS 0.0f
#define LIQUID_SOURCE_PARTICLE_SPACING (LIQUID_PARTICLE_RADIUS * 2.05f)
#define LIQUID_SOURCE_X_OFFSET 72.0f
#define LIQUID_SOURCE_Y 160.0f
#define LIQUID_SOURCE_VERTICAL_SPACING LIQUID_SOURCE_PARTICLE_SPACING
#define LIQUID_SOURCE_PARTICLES_PER_SIDE 4U
#define LIQUID_SOURCE_SPEED_X 440.0f
#define LIQUID_SOURCE_SPEED_Y 0.0f
#define LIQUID_EMIT_INTERVAL_SECONDS ((double)LIQUID_SOURCE_PARTICLE_SPACING / (double)LIQUID_SOURCE_SPEED_X)
#define LIQUID_SURFACE_CELL_SIZE (LIQUID_PARTICLE_RADIUS * 1.0f)
#define LIQUID_SURFACE_INFLUENCE_RADIUS (LIQUID_PARTICLE_RADIUS * 3.2f)
#define LIQUID_SURFACE_THRESHOLD 0.32f
#define LIQUID_SURFACE_ARGB 0xfffff000U
#define WAVE_PADDLE_WIDTH 42.0f
#define WAVE_PADDLE_HEIGHT 260.0f
#define WAVE_PADDLE_RIGHT_X (WORLD_WIDTH - WORLD_WALL_THICKNESS - WAVE_PADDLE_WIDTH * 0.5f - 18.0f)
#define WAVE_PADDLE_LEFT_X (WAVE_PADDLE_RIGHT_X - 220.0f)
#define WAVE_PADDLE_Y (WORLD_HEIGHT - WORLD_WALL_THICKNESS - WAVE_PADDLE_HEIGHT * 0.5f)
#define WAVE_PADDLE_PERIOD_SECONDS 4.8

#endif
