local Vector = include("src/Engine/Math/Vector.lua")
local Services = include("src/Engine/Core/Engine/Services.lua")
local EngineLayers = include("src/Engine/Core/Engine/Layers.lua")
local EngineLoop = include("src/Engine/Core/Engine/Loop.lua")
local EngineDebug = include("src/Engine/Core/Engine/Debug.lua")
local EngineSnapshot = include("src/Engine/Core/Engine/Snapshot.lua")

local Engine = {
	layers = {},
	master_camera = nil,
	clock = nil,
	debug_buffer = nil,
	debug_overlay = nil,
	next_object_id = 0,
	sorted_layer_ids = {},
	debug = DEBUG or false,
	profiler_enabled = true,
	debug_overlay_enabled = DEBUG or false,
	debug_guides_enabled = false,
	w = 16 * 64,
	h = 16 * 32,
	gravity = Vector:new({
		y = 200
	}),
	fill_color = 1,
	stroke_color = 5,
	ensureServices = Services.ensureServices,
	nextObjectId = Services.nextObjectId,
	createLayer = EngineLayers.createLayer,
	getLayer = EngineLayers.getLayer,
	on = Services.on,
	once = Services.once,
	off = Services.off,
	emit = Services.emit,
	linkCameras = EngineLayers.linkCameras,
	setMasterCamera = EngineLayers.setMasterCamera,
	appendDebug = Services.appendDebug,
	clearDebug = Services.clearDebug,
	registerClass = Services.registerClass,
	registerClasses = Services.registerClasses,
	saveSnapshot = Services.saveSnapshot,
	loadSnapshot = Services.loadSnapshot,
	saveObject = Services.saveObject,
	loadObject = Services.loadObject,
	save = Services.save,
	load = Services.load,
	saveExists = Services.saveExists,
	getSaveInfo = Services.getSaveInfo,
	update = EngineLoop.update,
	draw = EngineLoop.draw,
	start = EngineLoop.start,
	stop = EngineLoop.stop,
	debug_state = EngineDebug.debug_state,
	debug_layer = EngineDebug.debug_layer,
	toSnapshot = EngineSnapshot.toSnapshot,
	applySnapshot = EngineSnapshot.applySnapshot,
}

return Engine
